package com.indieniinja.server;

import com.indieniinja.network.EnemyState;
import com.indieniinja.network.NPCState;
import com.indieniinja.network.InputCommand;
import com.indieniinja.network.MessageType;
import com.indieniinja.network.PickupState;
import com.indieniinja.network.PlatformState;
import com.indieniinja.network.PlayerState;
import com.indieniinja.network.WireCodec;
import com.indieniinja.network.WorldRoomDescriptor;
import com.indieniinja.network.WorldSnapshot;
import com.indieniinja.sim.GameSimulator;
import com.indieniinja.sim.InputRecorder;
import com.indieniinja.sim.LevelLayout;
import com.indieniinja.world.WorldGraph;
import com.indieniinja.world.puzzle.PuzzlePlan;
import com.indieniinja.world.puzzle.PuzzlePlanner;
import com.indieniinja.sim.SimPlayer;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.channel.Channel;
import java.util.concurrent.locks.LockSupport;
import java.util.zip.CRC32;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * 60 Hz zone simulation loop — runs on a dedicated platform thread.
 *
 * Java equivalent of Python's network/server.py _zone_simulation_loop coroutine.
 *
 * Key design decisions:
 *  - LockSupport.parkNanos for sub-millisecond sleep precision (avoids
 *    Thread.sleep(16) quantization on Windows which has ~15ms minimum)
 *  - AtomicReference<InputCommand> on PlayerRecord — Netty I/O thread writes,
 *    this loop reads — zero lock on the hot path
 *  - Encode snapshot once, write to all zone members (zero-copy multicast)
 *  - Broadcast every 3rd tick (20 Hz) matching Python server behaviour
 *  - Full snapshot every FULL_SNAPSHOT_INTERVAL broadcasts (~3 seconds)
 */
public final class ZoneSimulationLoop implements Runnable {

    private static final Logger log = LoggerFactory.getLogger(ZoneSimulationLoop.class);

    static final long TICK_NS              = 1_000_000_000L / 60;  // 16,666,666 ns
    static final int  BROADCAST_EVERY      = 3;    // 20 Hz — matches Python
    static final int  FULL_SNAPSHOT_EVERY  = 60;   // 3 s full snapshot

    /** Idle zone reaper: tear down zone after this many ms without any player. */
    static final long IDLE_TTL_MS = 120_000L;  // 120 s — matches Python

    /**
     * Feature flag for the new post-processing pipeline.
     *
     * When false (default) the existing LevelLayout.buildUnifiedWorldLayout path
     * is used unchanged.  Flip to true once EntityPlanner + RoomPostProcessor are
     * wired (Phase 2) to activate the extended pipeline.
     */
    static boolean NEW_PIPELINE_ENABLED = true;

    private final ZoneInstance                      zone;
    private final GameSession                       session;
    private final AtomicBoolean                     shutdown;
    /** Shared zone registry — needed to get/create room zones during crossings. */
    private final ConcurrentHashMap<String, ZoneInstance> allZones;
    /** Executor that owns all sim loop threads — used to start new zone loops. */
    private final ExecutorService                   executor;
    /** Input recorder — active when recording flag is set in session. */
    private final InputRecorder recorder = new InputRecorder();
    /** Monotonically increasing tick counter for this zone loop. */
    private long tickCount = 0L;

    public ZoneSimulationLoop(ZoneInstance zone, GameSession session, AtomicBoolean shutdown,
                              ConcurrentHashMap<String, ZoneInstance> allZones,
                              ExecutorService executor) {
        this.zone     = zone;
        this.session  = session;
        this.shutdown = shutdown;
        this.allZones = allZones;
        this.executor = executor;
    }

    // ── Simulator init ────────────────────────────────────────────────────────

    /**
     * Build and attach a GameSimulator to this zone using the LevelLayout.
     * Called once before the loop starts (from ServerProtocolHandler.getOrCreateZone).
     */
    /**
     * Default rooms per hub world — mirrors Python hub_manager.py room_count defaults.
     * Small enough that generation is fast but large enough for meaningful exploration.
     */
    private static final int DEFAULT_ROOMS = 12;

    public static void initSimulator(ZoneInstance zone) {
        // Idempotent: skip if already initialized.
        if (zone.simulator != null) return;

        // WorldGraph may be pre-generated by ServerProtocolHandler.
        // Re-generate only if absent.
        WorldGraph graph = zone.worldGraph;
        if (graph == null) {
            graph = WorldGraph.generate(zone.seed, DEFAULT_ROOMS, WorldGraph.WorldShape.BLOB);
            zone.worldGraph = graph;
        }

        // ── Compute megamap min grid coords ──────────────────────────────────
        int minGX = Integer.MAX_VALUE, minGY = Integer.MAX_VALUE;
        for (WorldGraph.RoomNode room : graph.allRooms()) {
            if (room.gridX < minGX) minGX = room.gridX;
            if (room.gridY < minGY) minGY = room.gridY;
        }
        zone.megamapMinGridX = minGX;
        zone.megamapMinGridY = minGY;

        // ── Build unified world layout covering all rooms ─────────────────────
        LevelLayout layout;
        if (NEW_PIPELINE_ENABLED) {
            layout = buildUnifiedLayoutViaPostProcessor(graph, zone);
        } else {
            layout = LevelLayout.buildUnifiedWorldLayout(graph, zone.masterHubId);
        }

        // Hub zones: HubStateMachine is the sole authority for NPCs.
        // Clear layout-seeded NPCs so they don't clash with the hub FSM roster.
        // (EntityPlanner places lore/shop/crafter in every room including START;
        //  tickHubEvolution would wipe them at t=1s anyway — skip the churn.)
        layout.npcSpawns.clear();

        zone.simulator = new GameSimulator(graph.startRoom().seed, zone.hubId, layout);
        zone.simulator.setMode(zone.gameMode, zone.arcadeDepth, zone.arcadeRooms);

        // Initialise hub evolution state machine (one per zone, keyed by masterHubId)
        if (zone.hubStateMachine == null) {
            zone.hubStateMachine = new com.indieniinja.world.HubStateMachine(zone.masterHubId);
        }

        // Spawn position is in world-space from the unified layout
        zone.spawnX = layout.spawnX;
        zone.spawnY = layout.spawnY;

        // Set current room from start room
        WorldGraph.RoomNode startRoom = graph.startRoom();
        zone.currentRoomSeed     = startRoom.seed;
        zone.currentRoomGridX    = startRoom.gridX;
        zone.currentRoomGridY    = startRoom.gridY;
        zone.currentNeighborDirs = new java.util.ArrayList<>(startRoom.neighborDirs());
        zone.currentRoomType     = startRoom.type.wire();

        log.info("[Zone {}] unified world: {} rooms, megamapMin=({},{}), spawn=({},{})",
            zone.hubId, graph.size(), minGX, minGY, (int)zone.spawnX, (int)zone.spawnY);
    }

    /**
     * New-pipeline variant of buildUnifiedWorldLayout.
     *
     * Generates a PuzzlePlan once for the hub, then runs RoomPostProcessor on
     * every room so AbilityLayer, PuzzleLayer, and EntityPlanner are active for
     * the full world.  Delegates tile stitching and spawn offsetting to
     * LevelLayout.buildUnifiedWorldLayoutFromPlan.
     */
    private static LevelLayout buildUnifiedLayoutViaPostProcessor(
            WorldGraph graph, ZoneInstance zone) {

        // Generate and cache PuzzlePlan once per hub lifetime
        if (zone.puzzlePlan == null) {
            zone.puzzlePlan = PuzzlePlanner.plan(graph, zone.worldSeed);
            if (Boolean.getBoolean("ninja.debug.worldgen")) {
                com.indieniinja.world.postprocess.RoomContentDebugger.printPlan(
                    graph, zone.puzzlePlan);
            }
            log.info("[Zone {}] PuzzlePlan: {} edge gates, {} puzzle rooms",
                zone.hubId,
                zone.puzzlePlan.edgeGates.size(),
                zone.puzzlePlan.roomPuzzles.size());
        }

        return LevelLayout.buildUnifiedWorldLayoutFromPlan(
            graph, zone.puzzlePlan, zone.masterHubId);
    }

    @Override
    public void run() {
        // Phase B: initialise the server-side GameSimulator for this zone
        initSimulator(zone);
        log.info("[Zone {}] simulation loop started", zone.hubId);

        // Start recording if enabled via system property -Dninja.record=true
        boolean doRecord = Boolean.getBoolean("ninja.record");
        if (doRecord) recorder.startRecording(zone.seed);
        long nextTickNs   = System.nanoTime();
        int  broadcastCtr = 0;

        while (!shutdown.get()) {
            long now = System.nanoTime();

            if (now < nextTickNs) {
                // Sleep until next tick — use parkNanos for precision
                long sleepNs = nextTickNs - now;
                if (sleepNs > 1_000_000L) {
                    // More than 1ms to go — sleep most of it
                    LockSupport.parkNanos(sleepNs - 500_000L);
                }
                // Spin the last ~0.5ms for precision
                while (System.nanoTime() < nextTickNs) {
                    Thread.onSpinWait();
                }
            }

            nextTickNs += TICK_NS;

            // ── Simulate one tick ─────────────────────────────────────────────
            simulateTick();
            zone.frame.incrementAndGet();
            updateCurrentRoom();

            // ── Broadcast ─────────────────────────────────────────────────────
            if (++broadcastCtr >= BROADCAST_EVERY) {
                broadcastCtr = 0;
                boolean fullSnap = (++zone.fullSnapCountdown >= FULL_SNAPSHOT_EVERY);
                if (fullSnap) {
                    zone.fullSnapCountdown = 0;
                    zone.deltaEncoder.reset();
                }
                broadcastWorldState(fullSnap);
            }

            // ── Idle zone reaping ─────────────────────────────────────────────
            if (zone.isEmpty()) {
                long idleMs = System.currentTimeMillis() - zone.lastActivityMs;
                if (idleMs > IDLE_TTL_MS) {
                    log.info("[Zone {}] idle for {}s — shutting down", zone.hubId, idleMs / 1000);
                    break;
                }
            }
        }

        log.info("[Zone {}] simulation loop stopped", zone.hubId);

        // Save recording if active
        if (recorder.isRecording()) {
            try {
                java.nio.file.Path replayDir = java.nio.file.Paths.get("user_data", "replays");
                java.nio.file.Files.createDirectories(replayDir);
                String fname = "replay_" + zone.hubId + "_" + System.currentTimeMillis() + ".ndjson";
                recorder.stopRecording(replayDir.resolve(fname));
                log.info("[Zone {}] replay saved to {}", zone.hubId, fname);
            } catch (java.io.IOException e) {
                log.warn("[Zone {}] failed to save replay: {}", zone.hubId, e.getMessage());
            }
        }
    }

    // ── Simulation tick ───────────────────────────────────────────────────────

    /**
     * Phase B: drive the Java GameSimulator one tick.
     *
     * Player positions remain client-authoritative (written from INPUT messages
     * by ServerProtocolHandler into PlayerRecord.posX/Y). The simulator syncs
     * each SimPlayer's physics state from the PlayerRecord before stepping, so
     * enemies and pickups respond to accurate player positions.
     *
     * Phase C will flip players to full server-authoritative movement.
     */
    private void simulateTick() {
        GameSimulator sim = zone.simulator;
        if (sim == null) return;

        // Server-authoritative physics: player positions are owned by the server sim.
        // PlayerRecord.posX/Y is only used for the initial spawn — after that the
        // sim drives positions, and we write results BACK to PlayerRecord for broadcast.
        java.util.Map<Integer, InputCommand> inputs = new java.util.LinkedHashMap<>();
        for (String pid : zone.playerIds) {
            PlayerRecord pr = session.players.get(pid);
            if (pr == null) continue;

            SimPlayer sp = sim.getPlayers().get(pr.slot);
            if (sp == null) {
                float sx, sy;
                if (pr.explicitSpawnSet) {
                    // Transitioning player: use door-entry coords set by transitionPlayerToRoom()
                    sx = pr.posX;
                    sy = pr.posY;
                    pr.explicitSpawnSet = false;
                } else {
                    // Fresh join: use layout-detected safe spawn (always set by initSimulator before
                    // the tick loop starts — no fallback to pr.posX/Y which defaults to 0,0). NET-1
                    sx = zone.spawnX;
                    sy = zone.spawnY;
                }
                SimPlayer newSp = new SimPlayer(pid, pr.slot, sx, sy);
                newSp.health    = pr.health;
                newSp.facing    = pr.facing;
                newSp.animState = pr.animState;
                sim.addPlayer(newSp);
                sp = newSp;
            }
            // Do NOT overwrite sp.physics from pr — let the sim own positions.

            InputCommand cmd = pr.latestInput.get();
            if (cmd != null) {
                inputs.put(pr.slot, cmd);
                recorder.record(tickCount, pr.slot, cmd);
            }
        }

        tickCount++;
        sim.step(inputs);
        if (sim.drainPendingScriptedLoss()) {
            broadcastEvent(MessageType.SCRIPTED_LOSS, java.util.Map.of(
                "hub_id", zone.hubId,
                "event", "siren_scripted_loss"
            ));
        }
        if (zone.hubStateMachine != null) {
            for (String bossId : sim.drainPendingBossDefeatIds()) {
                zone.hubStateMachine.onBossDefeated(bossId);
                // Prevent once-per-second fallback diff from double-counting this boss.
                prevAliveBossIds.remove(bossId);
                log.info("[Zone {}] boss defeated (immediate): {}", zone.hubId, bossId);
            }
        }

        // Write authoritative physics results back to PlayerRecords for broadcast
        for (String pid : zone.playerIds) {
            PlayerRecord pr = session.players.get(pid);
            if (pr == null) continue;
            SimPlayer sp = sim.getPlayers().get(pr.slot);
            if (sp == null) continue;
            pr.posX     = sp.physics.x;
            pr.posY     = sp.physics.y;
            pr.velX     = sp.physics.vx;
            pr.velY     = sp.physics.vy;
            pr.facing    = sp.facing;
            pr.isDead    = sp.isDead;
            pr.health    = sp.health;
            pr.animState = sp.animState;
        }

        // ── Hub evolution: sync NPC roster once per second (every 60 ticks) ────
        // Skip frame 0 — layout NPCs are still being seeded; first sync at 1 s.
        long frame = zone.frame.get();
        if (frame > 0 && frame % 60 == 0 && zone.hubStateMachine != null) {
            tickHubEvolution(sim);
        }

        // ── Diagnostic: log player ground state every 60 ticks (1s) ─────────
        if (frame % 60 == 0 && !zone.playerIds.isEmpty()) {
            for (String pid : zone.playerIds) {
                PlayerRecord pr = session.players.get(pid);
                if (pr == null) continue;
                SimPlayer sp = sim.getPlayers().get(pr.slot);
                if (sp == null) continue;
                int tileCol     = (int)(sp.physics.x / 32);
                int tileFeetRow = (int)((sp.physics.y + sp.physics.height) / 32);
                int tileHeadRow = (int)(sp.physics.y / 32);
                log.debug("[Zone {}] player slot={} pos=({},{}) onGround={} " +
                    "anim={} tileCol={} feetRow={} headRow={} seed={}",
                    zone.hubId, pr.slot,
                    (int)sp.physics.x, (int)sp.physics.y, sp.physics.onGround,
                    sp.animState, tileCol, tileFeetRow, tileHeadRow,
                    zone.currentRoomSeed);
            }
        }
    }

    // ── Hub evolution ─────────────────────────────────────────────────────────

    /**
     * Called once per second (every 60 ticks).
     *
     * Detects boss defeats by comparing the live boss list against the previous
     * known-alive set, then syncs the NPC roster with the hub state machine:
     * spawns NPCs that should be active and despawns ones that shouldn't.
     */
    private final java.util.Set<String> prevAliveBossIds = new java.util.HashSet<>();

    private void tickHubEvolution(com.indieniinja.sim.GameSimulator sim) {
        // ── Boss defeat detection ─────────────────────────────────────────────
        // GameSimulator.getSnapshot() rebuilds the boss list from SimBoss each tick.
        // Compare with our previous snapshot to detect transitions alive→dead.
        com.indieniinja.network.WorldSnapshot snap = sim.getSnapshot(zone.frame.get());
        java.util.Set<String> nowAlive = new java.util.HashSet<>();
        for (com.indieniinja.network.BossState b : snap.bosses) {
            if (b.alive) nowAlive.add(b.bossId);
        }
        for (String bid : prevAliveBossIds) {
            if (!nowAlive.contains(bid)) {
                // Boss was alive last second, now dead → defeat event
                zone.hubStateMachine.onBossDefeated(bid);
                log.info("[Zone {}] boss defeated: {}", zone.hubId, bid);
            }
        }
        prevAliveBossIds.clear();
        prevAliveBossIds.addAll(nowAlive);

        // ── NPC roster sync ───────────────────────────────────────────────────
        java.util.List<String> desiredTypes = zone.hubStateMachine.activeNpcTypes();

        // Collect NPCs to remove first — never modify the list while iterating it
        java.util.List<com.indieniinja.sim.SimNPC> toRemove = new java.util.ArrayList<>();
        for (com.indieniinja.sim.SimNPC npc : sim.getNpcs()) {
            if (!desiredTypes.contains(npc.type)) toRemove.add(npc);
        }
        for (com.indieniinja.sim.SimNPC npc : toRemove) {
            sim.removeNpc(npc.id);
            log.info("[Zone {}] despawned NPC {} (type={})", zone.hubId, npc.id, npc.type);
        }

        // Spawn NPCs whose type should be active but aren't present
        java.util.Set<String> liveTypes = new java.util.HashSet<>();
        for (com.indieniinja.sim.SimNPC npc : sim.getNpcs()) liveTypes.add(npc.type);
        for (String desiredType : desiredTypes) {
            if (!liveTypes.contains(desiredType)) {
                // Spawn near zone spawn point
                String npcId = zone.hubId + "_hub_npc_" + desiredType + "_" + System.nanoTime();
                float sx = zone.spawnX + 64f;   // offset slightly from player spawn
                float sy = zone.spawnY;
                com.indieniinja.sim.SimNPC npc = new com.indieniinja.sim.SimNPC(
                    npcId, desiredType, sx, sy,
                    com.indieniinja.sim.SimNPC.DEFAULT_WIDTH,
                    com.indieniinja.sim.SimNPC.DEFAULT_HEIGHT,
                    sx - 96f, sx + 96f);
                sim.addNpc(npc);
                log.info("[Zone {}] spawned NPC {} (type={})", zone.hubId, npcId, desiredType);
            }
        }
    }

    // ── Room position derivation ──────────────────────────────────────────────

    private static final int ROOM_PX =
        com.indieniinja.physics.PhysicsConstants.ROOM_WIDTH_TILES *
        com.indieniinja.physics.PhysicsConstants.TILE_SIZE;   // 128 * 32 = 4096

    /**
     * After each tick, derive the zone's current room from the first player's
     * world-space position.  This replaces the old checkRoomCrossings() which
     * moved players between per-room ZoneInstances (causing the teleport glitch
     * and boundary resistance).  With the unified world layout, players simply
     * walk anywhere — no zone transitions for intra-hub movement.
     *
     * Updates zone.currentRoomGridX/Y for the minimap and snapshot broadcast.
     *
     * Hysteresis: the player must be at least HYSTERESIS_PX past the entry edge
     * before the room flip is committed, preventing rapid oscillation when
     * standing near a boundary.
     */
    private static final float ROOM_HYSTERESIS_PX = 64f;   // 2 tiles past boundary

    private void updateCurrentRoom() {
        if (zone.simulator == null || zone.worldGraph == null) return;

        for (String pid : zone.playerIds) {
            PlayerRecord pr = session.players.get(pid);
            if (pr == null) continue;
            SimPlayer sp = zone.simulator.getPlayers().get(pr.slot);
            if (sp == null) continue;

            int newGX = (int) Math.floor(sp.physics.x / ROOM_PX) + zone.megamapMinGridX;
            int newGY = (int) Math.floor(sp.physics.y / ROOM_PX) + zone.megamapMinGridY;

            // No change — fast path
            if (newGX == zone.currentRoomGridX && newGY == zone.currentRoomGridY) break;

            // Hysteresis: player must be HYSTERESIS_PX past the entry edge.
            // For a rightward crossing into newGX: local x from room origin ≥ HYSTERESIS.
            // For a leftward crossing into newGX:  local x from room origin ≤ ROOM_PX − HYSTERESIS.
            float localX = sp.physics.x - (newGX - zone.megamapMinGridX) * (float) ROOM_PX;
            float localY = sp.physics.y - (newGY - zone.megamapMinGridY) * (float) ROOM_PX;
            boolean xOk = newGX == zone.currentRoomGridX
                || (newGX > zone.currentRoomGridX && localX >= ROOM_HYSTERESIS_PX)
                || (newGX < zone.currentRoomGridX && localX <= ROOM_PX - ROOM_HYSTERESIS_PX);
            boolean yOk = newGY == zone.currentRoomGridY
                || (newGY > zone.currentRoomGridY && localY >= ROOM_HYSTERESIS_PX)
                || (newGY < zone.currentRoomGridY && localY <= ROOM_PX - ROOM_HYSTERESIS_PX);
            if (!xOk || !yOk) break;  // not far enough past boundary yet

            WorldGraph.RoomNode room = zone.worldGraph.roomAt(newGX, newGY);
            if (room != null) {
                zone.currentRoomGridX    = newGX;
                zone.currentRoomGridY    = newGY;
                zone.currentRoomSeed     = room.seed;
                zone.currentRoomType     = room.type.wire();
                zone.currentNeighborDirs = new java.util.ArrayList<>(room.neighborDirs());
            }
            break;  // one player is enough
        }
    }

    // ── Broadcast ─────────────────────────────────────────────────────────────

    private void broadcastWorldState(boolean fullSnapshot) {
        List<PlayerRecord> zonePlayers = playersInZone();
        if (zonePlayers.isEmpty()) return;

        WorldSnapshot snap = buildSnapshot(fullSnapshot, zonePlayers);
        Map<String, Object> payload = snap.toMap();

        // Persist full snapshot to Redis so reconnecting clients get immediate state
        if (fullSnapshot) {
            session.zoneStateCache.put(zone.hubId, payload);
        }

        byte[] encoded;
        try {
            encoded = WireCodec.encodeBody(MessageType.WORLD_STATE, payload);
        } catch (Exception ex) {
            log.error("[Zone {}] snapshot encode error: {}", zone.hubId, ex.getMessage());
            return;
        }

        // Write once-encoded bytes to all zone members — zero re-encoding
        for (PlayerRecord p : zonePlayers) {
            Channel ch = p.channel;
            if (ch.isActive()) {
                ByteBuf buf = Unpooled.wrappedBuffer(encoded);
                // LengthFieldPrepender in the Netty pipeline adds the 4-byte header
                ch.writeAndFlush(buf).addListener(f -> {
                    if (!f.isSuccess()) {
                        log.warn("[Zone {}] write failed for player {}: {}",
                            zone.hubId, p.playerId, f.cause().getMessage());
                    }
                });
            }
        }
    }

    private void broadcastEvent(String messageType, java.util.Map<String, Object> payload) {
        List<PlayerRecord> zonePlayers = playersInZone();
        if (zonePlayers.isEmpty()) return;
        byte[] encoded;
        try {
            encoded = WireCodec.encodeBody(messageType, payload);
        } catch (Exception ex) {
            log.error("[Zone {}] event encode error ({}): {}", zone.hubId, messageType, ex.getMessage());
            return;
        }
        for (PlayerRecord p : zonePlayers) {
            Channel ch = p.channel;
            if (ch == null || !ch.isActive()) continue;
            ByteBuf buf = Unpooled.wrappedBuffer(encoded);
            ch.writeAndFlush(buf).addListener(f -> {
                if (!f.isSuccess()) {
                    log.warn("[Zone {}] event write failed for {}: {}",
                        zone.hubId, p.playerId, f.cause().getMessage());
                }
            });
        }
    }

    /**
     * Phase B: get snapshot from GameSimulator (enemies + pickups + platforms included).
     * Delta encoding applied on top for bandwidth efficiency.
     */
    private WorldSnapshot buildSnapshot(boolean full, List<PlayerRecord> zonePlayers) {
        GameSimulator sim = zone.simulator;

        // Full snapshot from the authoritative simulator (all entities in world-space)
        WorldSnapshot snap = (sim != null)
            ? sim.getSnapshot(zone.frame.get())
            : buildFallbackSnapshot(zonePlayers);

        // Current room grid coords (derived each tick from player position by updateCurrentRoom())
        snap.roomGridX    = zone.currentRoomGridX;
        snap.roomGridY    = zone.currentRoomGridY;
        snap.roomType     = zone.currentRoomType;
        snap.neighborDirs = zone.currentNeighborDirs;
        // Keep seed = zone seed (megamap is built from worldRooms list, not single room seed)
        snap.isDelta = !full;

        // Send full world room layout on full snapshots so the client can build the megamap.
        if (full && zone.worldGraph != null) {
            for (WorldGraph.RoomNode room : zone.worldGraph.allRooms()) {
                WorldRoomDescriptor d = new WorldRoomDescriptor();
                d.gridX       = room.gridX;
                d.gridY       = room.gridY;
                d.seed        = room.seed;
                d.roomType    = room.type.wire();
                d.neighborDirs.addAll(room.neighborDirs());
                d.biomeIndex  = room.biomeIndex;
                snap.worldRooms.add(d);
            }
        }

        // Hub evolution state — always stamped so client StoryManager stays in sync
        if (zone.hubStateMachine != null) {
            snap.hubState = zone.hubStateMachine.getState().name();
        }

        // Compute frameHash over the full authoritative state (before delta encoding)
        // so clients can detect desync by comparing with their local simulation hash.
        snap.frameHash = computeFrameHash(snap);

        if (!full) {
            // Swap full lists with delta lists computed by DeltaEncoder
            List<EnemyState>    allEnemies   = snap.enemies;
            List<PickupState>   allPickups   = snap.pickups;
            List<PlatformState> allPlatforms = snap.platformStates;

            snap.enemies        = Collections.emptyList();
            snap.pickups        = Collections.emptyList();
            snap.platformStates = Collections.emptyList();

            snap.enemiesChanged   = zone.deltaEncoder.enemiesChanged(allEnemies);
            snap.enemiesRemoved   = zone.deltaEncoder.enemiesRemoved(allEnemies);
            snap.pickupsChanged   = zone.deltaEncoder.pickupsChanged(allPickups);
            snap.pickupsRemoved   = zone.deltaEncoder.pickupsRemoved(allPickups);
            snap.platformsChanged = zone.deltaEncoder.platformsChanged(allPlatforms);
            snap.platformsRemoved = zone.deltaEncoder.platformsRemoved(allPlatforms);
        }

        // Overflow entities no longer needed: all entities are in one unified world-space sim.

        return snap;
    }

    /** Fallback for the brief window before the simulator is ready (rare). */
    private WorldSnapshot buildFallbackSnapshot(List<PlayerRecord> zonePlayers) {
        WorldSnapshot snap = new WorldSnapshot();
        snap.frame  = zone.frame.get();
        snap.seed   = zone.seed;
        snap.hubId  = zone.hubId;
        for (PlayerRecord pr : zonePlayers) {
            PlayerState ps = new PlayerState();
            ps.playerId  = pr.playerId;
            ps.slot      = pr.slot;
            ps.posX      = pr.posX;
            ps.posY      = pr.posY;
            ps.velX      = pr.velX;
            ps.velY      = pr.velY;
            ps.health    = pr.health;
            ps.facing    = pr.facing;
            ps.isDead    = pr.isDead;
            ps.animState = pr.animState;
            snap.players.add(ps);
        }
        return snap;
    }

    /**
     * CRC32 hash of the authoritative world state at this frame.
     * Covers enemy positions/hp, pickup liveness, and player positions —
     * enough for clients to detect a simulation desync without hashing every field.
     * Package-private so NetworkingDesyncTest can call it directly.
     */
    static long computeFrameHash(WorldSnapshot snap) {
        CRC32 crc = new CRC32();
        for (EnemyState e : snap.enemies) {
            updateCrcFloat(crc, e.x);
            updateCrcFloat(crc, e.y);
            crc.update(e.hp);
        }
        for (PickupState p : snap.pickups) {
            updateCrcFloat(crc, p.x);
            updateCrcFloat(crc, p.y);
            crc.update(p.alive ? 1 : 0);
        }
        for (PlayerState p : snap.players) {
            updateCrcFloat(crc, p.posX);
            updateCrcFloat(crc, p.posY);
            crc.update(p.health);
        }
        return crc.getValue();
    }

    private static void updateCrcFloat(CRC32 crc, float v) {
        int bits = Float.floatToRawIntBits(v);
        crc.update((bits >>> 24) & 0xFF);
        crc.update((bits >>> 16) & 0xFF);
        crc.update((bits >>>  8) & 0xFF);
        crc.update(bits          & 0xFF);
    }

    private List<PlayerRecord> playersInZone() {
        List<PlayerRecord> result = new ArrayList<>(zone.playerIds.size());
        for (String pid : zone.playerIds) {
            PlayerRecord pr = session.players.get(pid);
            if (pr != null) result.add(pr);
        }
        return result;
    }
}
