package com.indieniinja.server;

import com.indieniinja.network.EnemyState;
import com.indieniinja.network.InputCommand;
import com.indieniinja.network.MessageType;
import com.indieniinja.network.PickupState;
import com.indieniinja.network.PlatformState;
import com.indieniinja.network.PlayerState;
import com.indieniinja.network.WireCodec;
import com.indieniinja.network.WorldRoomDescriptor;
import com.indieniinja.network.WorldSnapshot;
import com.indieniinja.sim.GameSimulator;
import com.indieniinja.sim.LevelLayout;
import com.indieniinja.world.WorldGraph;
import com.indieniinja.sim.SimPlayer;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.channel.Channel;
import java.util.concurrent.locks.LockSupport;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * 60 Hz zone simulation loop — runs on a dedicated platform thread.
 *
 * Java equivalent of Python's network/server.py _zone_simulation_loop coroutine.
 *
 * Key design decisions:
 *  - LockSupport.parkNanos for sub-millisecond sleep precision (avoids
 *    Thread.sleep(16) quantization on Windows which has ~15ms minimum)
 *  - AtomicReference<InputCommand> on PlayerRecord — Netty I/O thread writes,
 *    this loop reads — zero lock on the hot path
 *  - Encode snapshot once, write to all zone members (zero-copy multicast)
 *  - Broadcast every 3rd tick (20 Hz) matching Python server behaviour
 *  - Full snapshot every FULL_SNAPSHOT_INTERVAL broadcasts (~3 seconds)
 */
public final class ZoneSimulationLoop implements Runnable {

    private static final Logger log = LoggerFactory.getLogger(ZoneSimulationLoop.class);

    static final long TICK_NS              = 1_000_000_000L / 60;  // 16,666,666 ns
    static final int  BROADCAST_EVERY      = 3;    // 20 Hz — matches Python
    static final int  FULL_SNAPSHOT_EVERY  = 60;   // 3 s full snapshot

    /** Idle zone reaper: tear down zone after this many ms without any player. */
    static final long IDLE_TTL_MS = 120_000L;  // 120 s — matches Python

    private final ZoneInstance   zone;
    private final GameSession    session;
    private final AtomicBoolean  shutdown;

    public ZoneSimulationLoop(ZoneInstance zone, GameSession session, AtomicBoolean shutdown) {
        this.zone     = zone;
        this.session  = session;
        this.shutdown = shutdown;
    }

    // ── Simulator init ────────────────────────────────────────────────────────

    /**
     * Build and attach a GameSimulator to this zone using the LevelLayout.
     * Called once before the loop starts (from ServerProtocolHandler.getOrCreateZone).
     */
    /**
     * Default rooms per hub world — mirrors Python hub_manager.py room_count defaults.
     * Small enough that generation is fast but large enough for meaningful exploration.
     */
    private static final int DEFAULT_ROOMS = 12;

    public static void initSimulator(ZoneInstance zone) {
        // WorldGraph may be pre-generated by ServerProtocolHandler (start room)
        // or set when creating an adjacent-room zone.  Re-generate only if absent.
        WorldGraph graph = zone.worldGraph;
        if (graph == null) {
            graph = WorldGraph.generate(zone.seed, DEFAULT_ROOMS, WorldGraph.WorldShape.BLOB);
            zone.worldGraph = graph;
        }

        // Use the room this zone was created for (currentRoomGridX/Y pre-set for
        // adjacent rooms; for a brand-new hub zone use the graph's start room).
        WorldGraph.RoomNode startRoom = (zone.currentRoomSeed != 0)
            ? graph.roomAt(zone.currentRoomGridX, zone.currentRoomGridY)
            : graph.startRoom();
        if (startRoom == null) startRoom = graph.startRoom();
        zone.currentRoomSeed     = startRoom.seed;
        zone.currentRoomGridX    = startRoom.gridX;
        zone.currentRoomGridY    = startRoom.gridY;
        zone.currentNeighborDirs = new java.util.ArrayList<>(startRoom.neighborDirs());
        zone.currentRoomType     = startRoom.type.wire();

        // Build the procedural tile layout. Include adjacent room tile grids in
        // the SpatialHash so tiles visible at room boundaries have collision.
        java.util.Map<String, WorldGraph.RoomNode> adjacentRooms = new java.util.LinkedHashMap<>();
        for (String dir : startRoom.neighborDirs()) {
            WorldGraph.RoomNode nb = graph.neighborRoom(startRoom.gridX, startRoom.gridY, dir);
            if (nb != null) adjacentRooms.put(dir, nb);
        }
        LevelLayout layout = LevelLayout.buildProceduralLayout(
            startRoom.seed, startRoom.neighborDirs(), startRoom.type.wire(), adjacentRooms);
        zone.simulator = new GameSimulator(startRoom.seed, zone.hubId, layout);

        // Propagate layout spawn to zone so simulateTick uses the correct spawn position
        zone.spawnX = layout.spawnX;
        zone.spawnY = layout.spawnY;

        log.info("[Zone {}] WorldGraph: {} rooms (start={},{} seed={})",
            zone.hubId, graph.size(),
            startRoom.gridX, startRoom.gridY, startRoom.seed);
    }

    @Override
    public void run() {
        // Phase B: initialise the server-side GameSimulator for this zone
        initSimulator(zone);
        log.info("[Zone {}] simulation loop started", zone.hubId);
        long nextTickNs   = System.nanoTime();
        int  broadcastCtr = 0;

        while (!shutdown.get()) {
            long now = System.nanoTime();

            if (now < nextTickNs) {
                // Sleep until next tick — use parkNanos for precision
                long sleepNs = nextTickNs - now;
                if (sleepNs > 1_000_000L) {
                    // More than 1ms to go — sleep most of it
                    LockSupport.parkNanos(sleepNs - 500_000L);
                }
                // Spin the last ~0.5ms for precision
                while (System.nanoTime() < nextTickNs) {
                    Thread.onSpinWait();
                }
            }

            nextTickNs += TICK_NS;

            // ── Simulate one tick ─────────────────────────────────────────────
            simulateTick();
            zone.frame.incrementAndGet();
            checkRoomCrossings();

            // ── Broadcast ─────────────────────────────────────────────────────
            if (++broadcastCtr >= BROADCAST_EVERY) {
                broadcastCtr = 0;
                boolean fullSnap = (++zone.fullSnapCountdown >= FULL_SNAPSHOT_EVERY);
                if (fullSnap) {
                    zone.fullSnapCountdown = 0;
                    zone.deltaEncoder.reset();
                }
                broadcastWorldState(fullSnap);
            }

            // ── Idle zone reaping ─────────────────────────────────────────────
            if (zone.isEmpty()) {
                long idleMs = System.currentTimeMillis() - zone.lastActivityMs;
                if (idleMs > IDLE_TTL_MS) {
                    log.info("[Zone {}] idle for {}s — shutting down", zone.hubId, idleMs / 1000);
                    break;
                }
            }
        }

        log.info("[Zone {}] simulation loop stopped", zone.hubId);
    }

    // ── Simulation tick ───────────────────────────────────────────────────────

    /**
     * Phase B: drive the Java GameSimulator one tick.
     *
     * Player positions remain client-authoritative (written from INPUT messages
     * by ServerProtocolHandler into PlayerRecord.posX/Y). The simulator syncs
     * each SimPlayer's physics state from the PlayerRecord before stepping, so
     * enemies and pickups respond to accurate player positions.
     *
     * Phase C will flip players to full server-authoritative movement.
     */
    private void simulateTick() {
        GameSimulator sim = zone.simulator;
        if (sim == null) return;

        // Server-authoritative physics: player positions are owned by the server sim.
        // PlayerRecord.posX/Y is only used for the initial spawn — after that the
        // sim drives positions, and we write results BACK to PlayerRecord for broadcast.
        java.util.Map<Integer, InputCommand> inputs = new java.util.LinkedHashMap<>();
        for (String pid : zone.playerIds) {
            PlayerRecord pr = session.players.get(pid);
            if (pr == null) continue;

            SimPlayer sp = sim.getPlayers().get(pr.slot);
            if (sp == null) {
                float sx, sy;
                if (pr.explicitSpawnSet) {
                    // Transitioning player: use door-entry coords set by transitionPlayerToRoom()
                    sx = pr.posX;
                    sy = pr.posY;
                    pr.explicitSpawnSet = false;
                } else {
                    // Fresh join: use layout-detected safe spawn, fall back to PlayerRecord default
                    sx = zone.spawnX != 0 ? zone.spawnX : pr.posX;
                    sy = zone.spawnY != 0 ? zone.spawnY : pr.posY;
                }
                SimPlayer newSp = new SimPlayer(pid, pr.slot, sx, sy);
                newSp.health    = pr.health;
                newSp.facing    = pr.facing;
                newSp.animState = pr.animState;
                sim.addPlayer(newSp);
                sp = newSp;
            }
            // Do NOT overwrite sp.physics from pr — let the sim own positions.

            InputCommand cmd = pr.latestInput.get();
            if (cmd != null) inputs.put(pr.slot, cmd);
        }

        sim.step(inputs);

        // Write authoritative physics results back to PlayerRecords for broadcast
        for (String pid : zone.playerIds) {
            PlayerRecord pr = session.players.get(pid);
            if (pr == null) continue;
            SimPlayer sp = sim.getPlayers().get(pr.slot);
            if (sp == null) continue;
            pr.posX     = sp.physics.x;
            pr.posY     = sp.physics.y;
            pr.velX     = sp.physics.vx;
            pr.velY     = sp.physics.vy;
            pr.facing    = sp.facing;
            pr.isDead    = sp.isDead;
            pr.health    = sp.health;
            pr.animState = sp.animState;
        }

        // ── Diagnostic: log player ground state every 60 ticks (1s) ─────────
        long frame = zone.frame.get();
        if (frame % 60 == 0 && !zone.playerIds.isEmpty()) {
            for (String pid : zone.playerIds) {
                PlayerRecord pr = session.players.get(pid);
                if (pr == null) continue;
                SimPlayer sp = sim.getPlayers().get(pr.slot);
                if (sp == null) continue;
                int tileCol     = (int)(sp.physics.x / 32);
                int tileFeetRow = (int)((sp.physics.y + sp.physics.height) / 32);
                int tileHeadRow = (int)(sp.physics.y / 32);
                log.debug("[Zone {}] player slot={} pos=({},{}) onGround={} " +
                    "anim={} tileCol={} feetRow={} headRow={} seed={}",
                    zone.hubId, pr.slot,
                    (int)sp.physics.x, (int)sp.physics.y, sp.physics.onGround,
                    sp.animState, tileCol, tileFeetRow, tileHeadRow,
                    zone.currentRoomSeed);
            }
        }
    }

    // ── Room boundary crossing detection ─────────────────────────────────────

    private static final int ROOM_PX =
        com.indieniinja.physics.PhysicsConstants.ROOM_WIDTH_TILES *
        com.indieniinja.physics.PhysicsConstants.TILE_SIZE;   // 128 * 32 = 4096

    /**
     * After each tick, check whether any player has crossed a room boundary in
     * world-space.  When detected, adjust their room-local position and rebuild
     * the SpatialHash for the new room + its neighbors.
     *
     * No explicit door trigger points — the player simply walks through the
     * opening carved into the room's tile grid and their coordinates go outside
     * [0, ROOM_PX).  Math.floor handles negative positions correctly.
     */
    private void checkRoomCrossings() {
        WorldGraph graph = zone.worldGraph;
        if (graph == null || zone.simulator == null) return;

        for (String pid : zone.playerIds) {
            PlayerRecord pr = session.players.get(pid);
            if (pr == null) continue;
            SimPlayer sp = zone.simulator.getPlayers().get(pr.slot);
            if (sp == null) continue;

            int deltaX = (int) Math.floor((double) sp.physics.x / ROOM_PX);
            int deltaY = (int) Math.floor((double) sp.physics.y / ROOM_PX);
            if (deltaX == 0 && deltaY == 0) continue;

            int newGridX = zone.currentRoomGridX + deltaX;
            int newGridY = zone.currentRoomGridY + deltaY;
            WorldGraph.RoomNode newRoom = graph.roomAt(newGridX, newGridY);
            if (newRoom == null) continue;  // world edge — leave physics to handle it

            // Adjust physics position to be room-local in the new room
            sp.physics.x -= deltaX * ROOM_PX;
            sp.physics.y -= deltaY * ROOM_PX;
            pr.posX = sp.physics.x;
            pr.posY = sp.physics.y;

            // Update zone current room
            zone.currentRoomGridX    = newGridX;
            zone.currentRoomGridY    = newGridY;
            zone.currentRoomSeed     = newRoom.seed;
            zone.currentRoomType     = newRoom.type.wire();
            zone.currentNeighborDirs = new java.util.ArrayList<>(newRoom.neighborDirs());

            // Rebuild SpatialHash: new room + all its neighbors
            java.util.Map<String, WorldGraph.RoomNode> neighbors = new java.util.LinkedHashMap<>();
            for (String dir : newRoom.neighborDirs()) {
                WorldGraph.RoomNode nb = graph.neighborRoom(newGridX, newGridY, dir);
                if (nb != null) neighbors.put(dir, nb);
            }
            com.indieniinja.sim.LevelLayout newLayout =
                com.indieniinja.sim.LevelLayout.buildProceduralLayout(
                    newRoom.seed, newRoom.neighborDirs(), newRoom.type.wire(), neighbors);
            zone.simulator.updateSpatialHash(newLayout.spatialHash);

            log.info("[Zone {}] player {} crossed → room ({},{}) seed={}",
                zone.hubId, pid, newGridX, newGridY, newRoom.seed);
        }
    }

    // ── Broadcast ─────────────────────────────────────────────────────────────

    private void broadcastWorldState(boolean fullSnapshot) {
        List<PlayerRecord> zonePlayers = playersInZone();
        if (zonePlayers.isEmpty()) return;

        WorldSnapshot snap = buildSnapshot(fullSnapshot, zonePlayers);
        Map<String, Object> payload = snap.toMap();

        byte[] encoded;
        try {
            encoded = WireCodec.encodeBody(MessageType.WORLD_STATE, payload);
        } catch (Exception ex) {
            log.error("[Zone {}] snapshot encode error: {}", zone.hubId, ex.getMessage());
            return;
        }

        // Write once-encoded bytes to all zone members — zero re-encoding
        for (PlayerRecord p : zonePlayers) {
            Channel ch = p.channel;
            if (ch.isActive()) {
                ByteBuf buf = Unpooled.wrappedBuffer(encoded);
                // LengthFieldPrepender in the Netty pipeline adds the 4-byte header
                ch.writeAndFlush(buf).addListener(f -> {
                    if (!f.isSuccess()) {
                        log.warn("[Zone {}] write failed for player {}: {}",
                            zone.hubId, p.playerId, f.cause().getMessage());
                    }
                });
            }
        }
    }

    /**
     * Phase B: get snapshot from GameSimulator (enemies + pickups + platforms included).
     * Delta encoding applied on top for bandwidth efficiency.
     */
    private WorldSnapshot buildSnapshot(boolean full, List<PlayerRecord> zonePlayers) {
        GameSimulator sim = zone.simulator;

        // Full snapshot from the authoritative simulator
        WorldSnapshot snap = (sim != null)
            ? sim.getSnapshot(zone.frame.get())
            : buildFallbackSnapshot(zonePlayers);

        // Override seed with the current room's derived seed so the client
        // generates the correct tile grid for this specific room.
        long roomSeed = zone.currentRoomSeed;
        if (roomSeed != 0) snap.seed = roomSeed;
        snap.roomGridX    = zone.currentRoomGridX;
        snap.roomGridY    = zone.currentRoomGridY;
        snap.roomType     = zone.currentRoomType;
        snap.neighborDirs = zone.currentNeighborDirs;
        snap.isDelta = !full;

        // Send full world room layout on full snapshots so the client can build the megamap.
        if (full && zone.worldGraph != null) {
            for (WorldGraph.RoomNode room : zone.worldGraph.allRooms()) {
                WorldRoomDescriptor d = new WorldRoomDescriptor();
                d.gridX       = room.gridX;
                d.gridY       = room.gridY;
                d.seed        = room.seed;
                d.roomType    = room.type.wire();
                d.neighborDirs.addAll(room.neighborDirs());
                d.biomeIndex  = room.biomeIndex;
                snap.worldRooms.add(d);
            }
        }

        if (!full) {
            // Swap full lists with delta lists computed by DeltaEncoder
            List<EnemyState>    allEnemies   = snap.enemies;
            List<PickupState>   allPickups   = snap.pickups;
            List<PlatformState> allPlatforms = snap.platformStates;

            snap.enemies        = Collections.emptyList();
            snap.pickups        = Collections.emptyList();
            snap.platformStates = Collections.emptyList();

            snap.enemiesChanged   = zone.deltaEncoder.enemiesChanged(allEnemies);
            snap.enemiesRemoved   = zone.deltaEncoder.enemiesRemoved(allEnemies);
            snap.pickupsChanged   = zone.deltaEncoder.pickupsChanged(allPickups);
            snap.pickupsRemoved   = zone.deltaEncoder.pickupsRemoved(allPickups);
            snap.platformsChanged = zone.deltaEncoder.platformsChanged(allPlatforms);
            snap.platformsRemoved = zone.deltaEncoder.platformsRemoved(allPlatforms);
        }

        return snap;
    }

    /** Fallback for the brief window before the simulator is ready (rare). */
    private WorldSnapshot buildFallbackSnapshot(List<PlayerRecord> zonePlayers) {
        WorldSnapshot snap = new WorldSnapshot();
        snap.frame  = zone.frame.get();
        snap.seed   = zone.seed;
        snap.hubId  = zone.hubId;
        for (PlayerRecord pr : zonePlayers) {
            PlayerState ps = new PlayerState();
            ps.playerId  = pr.playerId;
            ps.slot      = pr.slot;
            ps.posX      = pr.posX;
            ps.posY      = pr.posY;
            ps.velX      = pr.velX;
            ps.velY      = pr.velY;
            ps.health    = pr.health;
            ps.facing    = pr.facing;
            ps.isDead    = pr.isDead;
            ps.animState = pr.animState;
            snap.players.add(ps);
        }
        return snap;
    }

    private List<PlayerRecord> playersInZone() {
        List<PlayerRecord> result = new ArrayList<>(zone.playerIds.size());
        for (String pid : zone.playerIds) {
            PlayerRecord pr = session.players.get(pid);
            if (pr != null) result.add(pr);
        }
        return result;
    }
}
