package com.indieniinja.server;

import com.indieniinja.network.EnemyState;
import com.indieniinja.network.InputCommand;
import com.indieniinja.network.MessageType;
import com.indieniinja.network.PickupState;
import com.indieniinja.network.PlatformState;
import com.indieniinja.network.PlayerState;
import com.indieniinja.network.WireCodec;
import com.indieniinja.network.WorldRoomDescriptor;
import com.indieniinja.network.WorldSnapshot;
import com.indieniinja.sim.GameMode;
import com.indieniinja.sim.GameSimulator;
import com.indieniinja.sim.LevelLayout;
import com.indieniinja.world.WorldGraph;
import com.indieniinja.sim.SimPlayer;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.channel.Channel;
import java.util.concurrent.locks.LockSupport;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * 60 Hz zone simulation loop — runs on a dedicated platform thread.
 *
 * Java equivalent of Python's network/server.py _zone_simulation_loop coroutine.
 *
 * Key design decisions:
 *  - LockSupport.parkNanos for sub-millisecond sleep precision (avoids
 *    Thread.sleep(16) quantization on Windows which has ~15ms minimum)
 *  - AtomicReference<InputCommand> on PlayerRecord — Netty I/O thread writes,
 *    this loop reads — zero lock on the hot path
 *  - Encode snapshot once, write to all zone members (zero-copy multicast)
 *  - Broadcast every 3rd tick (20 Hz) matching Python server behaviour
 *  - Full snapshot every FULL_SNAPSHOT_INTERVAL broadcasts (~3 seconds)
 */
public final class ZoneSimulationLoop implements Runnable {

    private static final Logger log = LoggerFactory.getLogger(ZoneSimulationLoop.class);

    static final long TICK_NS              = 1_000_000_000L / 60;  // 16,666,666 ns
    static final int  BROADCAST_EVERY      = 3;    // 20 Hz — matches Python
    static final int  FULL_SNAPSHOT_EVERY  = 60;   // 3 s full snapshot

    /** Idle zone reaper: tear down zone after this many ms without any player. */
    static final long IDLE_TTL_MS = 120_000L;  // 120 s — matches Python

    private final ZoneInstance                      zone;
    private final GameSession                       session;
    private final AtomicBoolean                     shutdown;
    /** Shared zone registry — needed to get/create room zones during crossings. */
    private final ConcurrentHashMap<String, ZoneInstance> allZones;
    /** Executor that owns all sim loop threads — used to start new zone loops. */
    private final ExecutorService                   executor;

    public ZoneSimulationLoop(ZoneInstance zone, GameSession session, AtomicBoolean shutdown,
                              ConcurrentHashMap<String, ZoneInstance> allZones,
                              ExecutorService executor) {
        this.zone     = zone;
        this.session  = session;
        this.shutdown = shutdown;
        this.allZones = allZones;
        this.executor = executor;
    }

    // ── Simulator init ────────────────────────────────────────────────────────

    /**
     * Build and attach a GameSimulator to this zone using the LevelLayout.
     * Called once before the loop starts (from ServerProtocolHandler.getOrCreateZone).
     */
    /**
     * Default rooms per hub world — mirrors Python hub_manager.py room_count defaults.
     * Small enough that generation is fast but large enough for meaningful exploration.
     */
    private static final int DEFAULT_ROOMS = 12;

    public static void initSimulator(ZoneInstance zone) {
        // WorldGraph may be pre-generated by ServerProtocolHandler (start room)
        // or set when creating an adjacent-room zone.  Re-generate only if absent.
        WorldGraph graph = zone.worldGraph;
        if (graph == null) {
            graph = WorldGraph.generate(zone.seed, DEFAULT_ROOMS, WorldGraph.WorldShape.BLOB);
            zone.worldGraph = graph;
        }

        // Use the room this zone was created for (currentRoomGridX/Y pre-set for
        // adjacent rooms; for a brand-new hub zone use the graph's start room).
        WorldGraph.RoomNode startRoom = (zone.currentRoomSeed != 0)
            ? graph.roomAt(zone.currentRoomGridX, zone.currentRoomGridY)
            : graph.startRoom();
        if (startRoom == null) startRoom = graph.startRoom();
        zone.currentRoomSeed     = startRoom.seed;
        zone.currentRoomGridX    = startRoom.gridX;
        zone.currentRoomGridY    = startRoom.gridY;
        zone.currentNeighborDirs = new java.util.ArrayList<>(startRoom.neighborDirs());
        zone.currentRoomType     = startRoom.type.wire();

        // Build the procedural tile layout. Include adjacent room tile grids in
        // the SpatialHash so tiles visible at room boundaries have collision.
        java.util.Map<String, WorldGraph.RoomNode> adjacentRooms = new java.util.LinkedHashMap<>();
        for (String dir : startRoom.neighborDirs()) {
            WorldGraph.RoomNode nb = graph.neighborRoom(startRoom.gridX, startRoom.gridY, dir);
            if (nb != null) adjacentRooms.put(dir, nb);
        }
        LevelLayout layout = LevelLayout.buildProceduralLayout(
            startRoom.seed, startRoom.neighborDirs(), startRoom.type.wire(), adjacentRooms);
        zone.simulator = new GameSimulator(startRoom.seed, zone.hubId, layout);
        zone.simulator.setMode(zone.gameMode, zone.arcadeDepth, zone.arcadeRooms);

        // Propagate layout spawn to zone so simulateTick uses the correct spawn position
        zone.spawnX = layout.spawnX;
        zone.spawnY = layout.spawnY;

        log.info("[Zone {}] WorldGraph: {} rooms (start={},{} seed={})",
            zone.hubId, graph.size(),
            startRoom.gridX, startRoom.gridY, startRoom.seed);
    }

    @Override
    public void run() {
        // Phase B: initialise the server-side GameSimulator for this zone
        initSimulator(zone);
        log.info("[Zone {}] simulation loop started", zone.hubId);
        long nextTickNs   = System.nanoTime();
        int  broadcastCtr = 0;

        while (!shutdown.get()) {
            long now = System.nanoTime();

            if (now < nextTickNs) {
                // Sleep until next tick — use parkNanos for precision
                long sleepNs = nextTickNs - now;
                if (sleepNs > 1_000_000L) {
                    // More than 1ms to go — sleep most of it
                    LockSupport.parkNanos(sleepNs - 500_000L);
                }
                // Spin the last ~0.5ms for precision
                while (System.nanoTime() < nextTickNs) {
                    Thread.onSpinWait();
                }
            }

            nextTickNs += TICK_NS;

            // ── Simulate one tick ─────────────────────────────────────────────
            simulateTick();
            zone.frame.incrementAndGet();
            checkRoomCrossings();
            processPendingTransitions();

            // ── Broadcast ─────────────────────────────────────────────────────
            if (++broadcastCtr >= BROADCAST_EVERY) {
                broadcastCtr = 0;
                boolean fullSnap = (++zone.fullSnapCountdown >= FULL_SNAPSHOT_EVERY);
                if (fullSnap) {
                    zone.fullSnapCountdown = 0;
                    zone.deltaEncoder.reset();
                }
                broadcastWorldState(fullSnap);
            }

            // ── Idle zone reaping ─────────────────────────────────────────────
            if (zone.isEmpty()) {
                long idleMs = System.currentTimeMillis() - zone.lastActivityMs;
                if (idleMs > IDLE_TTL_MS) {
                    log.info("[Zone {}] idle for {}s — shutting down", zone.hubId, idleMs / 1000);
                    break;
                }
            }
        }

        log.info("[Zone {}] simulation loop stopped", zone.hubId);
    }

    // ── Simulation tick ───────────────────────────────────────────────────────

    /**
     * Phase B: drive the Java GameSimulator one tick.
     *
     * Player positions remain client-authoritative (written from INPUT messages
     * by ServerProtocolHandler into PlayerRecord.posX/Y). The simulator syncs
     * each SimPlayer's physics state from the PlayerRecord before stepping, so
     * enemies and pickups respond to accurate player positions.
     *
     * Phase C will flip players to full server-authoritative movement.
     */
    private void simulateTick() {
        GameSimulator sim = zone.simulator;
        if (sim == null) return;

        // Server-authoritative physics: player positions are owned by the server sim.
        // PlayerRecord.posX/Y is only used for the initial spawn — after that the
        // sim drives positions, and we write results BACK to PlayerRecord for broadcast.
        java.util.Map<Integer, InputCommand> inputs = new java.util.LinkedHashMap<>();
        for (String pid : zone.playerIds) {
            PlayerRecord pr = session.players.get(pid);
            if (pr == null) continue;

            SimPlayer sp = sim.getPlayers().get(pr.slot);
            if (sp == null) {
                float sx, sy;
                if (pr.explicitSpawnSet) {
                    // Transitioning player: use door-entry coords set by transitionPlayerToRoom()
                    sx = pr.posX;
                    sy = pr.posY;
                    pr.explicitSpawnSet = false;
                } else {
                    // Fresh join: use layout-detected safe spawn, fall back to PlayerRecord default
                    sx = zone.spawnX != 0 ? zone.spawnX : pr.posX;
                    sy = zone.spawnY != 0 ? zone.spawnY : pr.posY;
                }
                SimPlayer newSp = new SimPlayer(pid, pr.slot, sx, sy);
                newSp.health    = pr.health;
                newSp.facing    = pr.facing;
                newSp.animState = pr.animState;
                sim.addPlayer(newSp);
                sp = newSp;
            }
            // Do NOT overwrite sp.physics from pr — let the sim own positions.

            InputCommand cmd = pr.latestInput.get();
            if (cmd != null) inputs.put(pr.slot, cmd);
        }

        sim.step(inputs);

        // Write authoritative physics results back to PlayerRecords for broadcast
        for (String pid : zone.playerIds) {
            PlayerRecord pr = session.players.get(pid);
            if (pr == null) continue;
            SimPlayer sp = sim.getPlayers().get(pr.slot);
            if (sp == null) continue;
            pr.posX     = sp.physics.x;
            pr.posY     = sp.physics.y;
            pr.velX     = sp.physics.vx;
            pr.velY     = sp.physics.vy;
            pr.facing    = sp.facing;
            pr.isDead    = sp.isDead;
            pr.health    = sp.health;
            pr.animState = sp.animState;
        }

        // ── Diagnostic: log player ground state every 60 ticks (1s) ─────────
        long frame = zone.frame.get();
        if (frame % 60 == 0 && !zone.playerIds.isEmpty()) {
            for (String pid : zone.playerIds) {
                PlayerRecord pr = session.players.get(pid);
                if (pr == null) continue;
                SimPlayer sp = sim.getPlayers().get(pr.slot);
                if (sp == null) continue;
                int tileCol     = (int)(sp.physics.x / 32);
                int tileFeetRow = (int)((sp.physics.y + sp.physics.height) / 32);
                int tileHeadRow = (int)(sp.physics.y / 32);
                log.debug("[Zone {}] player slot={} pos=({},{}) onGround={} " +
                    "anim={} tileCol={} feetRow={} headRow={} seed={}",
                    zone.hubId, pr.slot,
                    (int)sp.physics.x, (int)sp.physics.y, sp.physics.onGround,
                    sp.animState, tileCol, tileFeetRow, tileHeadRow,
                    zone.currentRoomSeed);
            }
        }
    }

    // ── Room boundary crossing detection ─────────────────────────────────────

    private static final int ROOM_PX =
        com.indieniinja.physics.PhysicsConstants.ROOM_WIDTH_TILES *
        com.indieniinja.physics.PhysicsConstants.TILE_SIZE;   // 128 * 32 = 4096

    /**
     * After each tick, check whether any player has crossed a room boundary.
     * Player positions outside [0, ROOM_PX) indicate a crossing.
     *
     * Rather than updating zone-level room state (which would corrupt every
     * other player's world-space coordinates), we enqueue a PendingRoomTransition.
     * processPendingTransitions() handles the actual zone move after this tick.
     */
    private void checkRoomCrossings() {
        WorldGraph graph = zone.worldGraph;
        if (graph == null || zone.simulator == null) return;

        for (String pid : new ArrayList<>(zone.playerIds)) {
            PlayerRecord pr = session.players.get(pid);
            if (pr == null) continue;
            SimPlayer sp = zone.simulator.getPlayers().get(pr.slot);
            if (sp == null) continue;

            int deltaX = (int) Math.floor((double) sp.physics.x / ROOM_PX);
            int deltaY = (int) Math.floor((double) sp.physics.y / ROOM_PX);
            if (deltaX == 0 && deltaY == 0) continue;

            int newGridX = zone.currentRoomGridX + deltaX;
            int newGridY = zone.currentRoomGridY + deltaY;
            WorldGraph.RoomNode newRoom = graph.roomAt(newGridX, newGridY);
            if (newRoom == null) continue;  // world boundary — clamp physics elsewhere

            // Adjust physics position to room-local coordinates in the new room.
            // Use a SAFE_ENTRY buffer so the player doesn't immediately re-trigger
            // a crossing back: gravity would pull them through the floor/ceiling if
            // placed at y ≈ ROOM_PX (upward crossing) or y ≈ 0 (downward crossing).
            final float TILE      = com.indieniinja.physics.PhysicsConstants.TILE_SIZE;
            final float DOOR_THICK = 4 * TILE;   // "down"/"up" door rows = 4 tiles
            final float SAFE_ENTRY = DOOR_THICK + com.indieniinja.physics.PhysicsConstants.PLAYER_HEIGHT + 8;

            sp.physics.x -= deltaX * ROOM_PX;
            sp.physics.y -= deltaY * ROOM_PX;

            // Vertical: clamp entry so player lands safely above/below the door zone.
            if (deltaY == -1) {
                // Entered from below (jumped up): must not be at bottom of new room.
                sp.physics.y = Math.min(sp.physics.y, ROOM_PX - SAFE_ENTRY);
            } else if (deltaY == 1) {
                // Entered from above (fell down): must not be at top of new room.
                sp.physics.y = Math.max(sp.physics.y, SAFE_ENTRY - DOOR_THICK);
            }
            pr.posX = sp.physics.x;
            pr.posY = sp.physics.y;

            // Queue the zone transition — do NOT update zone.currentRoomGridX/Y here
            // because that would corrupt the room coordinates broadcast to other players.
            zone.pendingRoomTransitions.add(new ZoneInstance.PendingRoomTransition(
                pid, newGridX, newGridY, sp.physics.x, sp.physics.y));

            log.info("[Zone {}] player {} queued transition → room ({},{})",
                zone.hubId, pid, newGridX, newGridY);
        }
    }

    /**
     * Process room transitions queued by checkRoomCrossings().
     * Moves each transitioning player into the correct per-room ZoneInstance,
     * creating it if necessary, and sends WORLD_TRANSITION to that player.
     *
     * Safe to call from the sim thread: ConcurrentHashMap, Channel.writeAndFlush,
     * and PlayerRecord fields are all thread-safe.
     */
    private void processPendingTransitions() {
        ZoneInstance.PendingRoomTransition tr;
        while ((tr = zone.pendingRoomTransitions.poll()) != null) {
            final ZoneInstance.PendingRoomTransition transition = tr;
            doRoomTransition(transition);
        }
    }

    private void doRoomTransition(ZoneInstance.PendingRoomTransition tr) {
        PlayerRecord pr = session.players.get(tr.playerId());
        if (pr == null) return;

        WorldGraph graph = zone.worldGraph;
        if (graph == null) return;

        WorldGraph.RoomNode newRoom = graph.roomAt(tr.newGridX(), tr.newGridY());
        if (newRoom == null) return;

        String masterHubId = zone.masterHubId;
        String newKey = masterHubId + ":" + tr.newGridX() + ":" + tr.newGridY();

        // ── Remove player from current zone ────────────────────────────────────
        zone.playerIds.remove(tr.playerId());
        zone.lastActivityMs = System.currentTimeMillis();
        if (zone.simulator != null) zone.simulator.removePlayer(pr.slot);

        // ── Arcade EXIT: advance depth, generate fresh world ──────────────────
        if (zone.gameMode == GameMode.ARCADE && newRoom.type == WorldGraph.RoomType.EXIT) {
            int newDepth = zone.arcadeDepth + 1;
            int newRooms = zone.arcadeRooms + 2;   // scale up per depth
            long newWorldSeed = zone.worldSeed ^ (long)("depth" + newDepth).hashCode();
            WorldGraph newGraph = WorldGraph.generate(newWorldSeed, newRooms, WorldGraph.WorldShape.BLOB);
            WorldGraph.RoomNode startRoom = newGraph.startRoom();
            String arcadeKey = masterHubId + ":arcade:" + newDepth + ":" + startRoom.gridX + ":" + startRoom.gridY;

            ZoneInstance arcadeZone = allZones.computeIfAbsent(arcadeKey, k -> {
                ZoneInstance z = new ZoneInstance(
                    arcadeKey, masterHubId, newWorldSeed, zone.shape, newRooms,
                    newWorldSeed, startRoom.gridX * 32f, startRoom.gridY * 32f
                );
                z.worldGraph          = newGraph;
                z.currentRoomSeed     = startRoom.seed;
                z.currentRoomGridX    = startRoom.gridX;
                z.currentRoomGridY    = startRoom.gridY;
                z.currentNeighborDirs = new java.util.ArrayList<>(startRoom.neighborDirs());
                z.currentRoomType     = startRoom.type.wire();
                z.gameMode            = GameMode.ARCADE;
                z.arcadeDepth         = newDepth;
                z.arcadeRooms         = newRooms;
                AtomicBoolean sh = new AtomicBoolean(false);
                ZoneSimulationLoop loop = new ZoneSimulationLoop(z, session, sh, allZones, executor);
                executor.submit(loop);
                log.info("[Arcade] depth {} — new world seed={} rooms={} start=({},{})",
                    newDepth, newWorldSeed, newRooms, startRoom.gridX, startRoom.gridY);
                return z;
            });

            // Redirect player to the arcade depth+1 start zone
            pr.posX             = arcadeZone.spawnX;
            pr.posY             = arcadeZone.spawnY;
            pr.explicitSpawnSet = true;
            pr.hubId            = arcadeKey;
            arcadeZone.playerIds.add(tr.playerId());
            sendWorldTransition(pr, arcadeZone);
            log.info("[Arcade] {} advanced to depth {} → zone '{}'", tr.playerId(), newDepth, arcadeKey);
            return;
        }

        // ── Get or create the destination room's ZoneInstance ──────────────────
        ZoneInstance newZone = allZones.computeIfAbsent(newKey, k -> {
            ZoneInstance z = new ZoneInstance(
                newKey, masterHubId, zone.seed, zone.shape, zone.rooms,
                zone.worldSeed, tr.newX(), tr.newY()
            );
            z.worldGraph          = graph;
            z.currentRoomSeed     = newRoom.seed;
            z.currentRoomGridX    = tr.newGridX();
            z.currentRoomGridY    = tr.newGridY();
            z.currentNeighborDirs = new java.util.ArrayList<>(newRoom.neighborDirs());
            z.currentRoomType     = newRoom.type.wire();
            z.gameMode            = zone.gameMode;
            z.arcadeDepth         = zone.arcadeDepth;
            z.arcadeRooms         = zone.arcadeRooms;
            // Start a new sim loop for this room zone
            AtomicBoolean sh = new AtomicBoolean(false);
            ZoneSimulationLoop loop = new ZoneSimulationLoop(z, session, sh, allZones, executor);
            executor.submit(loop);
            log.info("[Zone] created room zone '{}' for crossing", newKey);
            return z;
        });

        // ── Set spawn position and add player to new zone ──────────────────────
        pr.posX             = tr.newX();
        pr.posY             = tr.newY();
        pr.explicitSpawnSet = true;
        pr.hubId            = newKey;
        newZone.playerIds.add(tr.playerId());

        // Same-hub room crossing: do NOT send WORLD_TRANSITION.
        // The client detects the room change from snap.roomGridX/Y and updates
        // the megamap offset smoothly — no entity-state reset, no visible teleport.
        // WORLD_TRANSITION is reserved for actual hub/world changes (portals, arcade depth).
        log.info("[Zone {}→{}] player {} moved to room ({},{})",
            zone.hubId, newKey, tr.playerId(), tr.newGridX(), tr.newGridY());
    }

    private void sendWorldTransition(PlayerRecord pr, ZoneInstance dest) {
        try {
            byte[] body = WireCodec.encodeBody(
                MessageType.WORLD_TRANSITION,
                Map.of(
                    "hub_id",     dest.hubId,
                    "seed",       dest.seed,
                    "shape",      dest.shape,
                    "rooms",      dest.rooms,
                    "world_seed", dest.worldSeed,
                    "spawn_x",    dest.spawnX,
                    "spawn_y",    dest.spawnY
                )
            );
            if (pr.channel.isActive()) {
                ByteBuf buf = Unpooled.wrappedBuffer(body);
                pr.channel.writeAndFlush(buf);
            }
        } catch (Exception ex) {
            log.error("[Zone] WORLD_TRANSITION send error: {}", ex.getMessage());
        }
    }

    // ── Broadcast ─────────────────────────────────────────────────────────────

    private void broadcastWorldState(boolean fullSnapshot) {
        List<PlayerRecord> zonePlayers = playersInZone();
        if (zonePlayers.isEmpty()) return;

        WorldSnapshot snap = buildSnapshot(fullSnapshot, zonePlayers);
        Map<String, Object> payload = snap.toMap();

        byte[] encoded;
        try {
            encoded = WireCodec.encodeBody(MessageType.WORLD_STATE, payload);
        } catch (Exception ex) {
            log.error("[Zone {}] snapshot encode error: {}", zone.hubId, ex.getMessage());
            return;
        }

        // Write once-encoded bytes to all zone members — zero re-encoding
        for (PlayerRecord p : zonePlayers) {
            Channel ch = p.channel;
            if (ch.isActive()) {
                ByteBuf buf = Unpooled.wrappedBuffer(encoded);
                // LengthFieldPrepender in the Netty pipeline adds the 4-byte header
                ch.writeAndFlush(buf).addListener(f -> {
                    if (!f.isSuccess()) {
                        log.warn("[Zone {}] write failed for player {}: {}",
                            zone.hubId, p.playerId, f.cause().getMessage());
                    }
                });
            }
        }
    }

    /**
     * Phase B: get snapshot from GameSimulator (enemies + pickups + platforms included).
     * Delta encoding applied on top for bandwidth efficiency.
     */
    private WorldSnapshot buildSnapshot(boolean full, List<PlayerRecord> zonePlayers) {
        GameSimulator sim = zone.simulator;

        // Full snapshot from the authoritative simulator
        WorldSnapshot snap = (sim != null)
            ? sim.getSnapshot(zone.frame.get())
            : buildFallbackSnapshot(zonePlayers);

        // Override seed with the current room's derived seed so the client
        // generates the correct tile grid for this specific room.
        long roomSeed = zone.currentRoomSeed;
        if (roomSeed != 0) snap.seed = roomSeed;
        snap.roomGridX    = zone.currentRoomGridX;
        snap.roomGridY    = zone.currentRoomGridY;
        snap.roomType     = zone.currentRoomType;
        snap.neighborDirs = zone.currentNeighborDirs;
        snap.isDelta = !full;

        // Send full world room layout on full snapshots so the client can build the megamap.
        if (full && zone.worldGraph != null) {
            for (WorldGraph.RoomNode room : zone.worldGraph.allRooms()) {
                WorldRoomDescriptor d = new WorldRoomDescriptor();
                d.gridX       = room.gridX;
                d.gridY       = room.gridY;
                d.seed        = room.seed;
                d.roomType    = room.type.wire();
                d.neighborDirs.addAll(room.neighborDirs());
                d.biomeIndex  = room.biomeIndex;
                snap.worldRooms.add(d);
            }
        }

        if (!full) {
            // Swap full lists with delta lists computed by DeltaEncoder
            List<EnemyState>    allEnemies   = snap.enemies;
            List<PickupState>   allPickups   = snap.pickups;
            List<PlatformState> allPlatforms = snap.platformStates;

            snap.enemies        = Collections.emptyList();
            snap.pickups        = Collections.emptyList();
            snap.platformStates = Collections.emptyList();

            snap.enemiesChanged   = zone.deltaEncoder.enemiesChanged(allEnemies);
            snap.enemiesRemoved   = zone.deltaEncoder.enemiesRemoved(allEnemies);
            snap.pickupsChanged   = zone.deltaEncoder.pickupsChanged(allPickups);
            snap.pickupsRemoved   = zone.deltaEncoder.pickupsRemoved(allPickups);
            snap.platformsChanged = zone.deltaEncoder.platformsChanged(allPlatforms);
            snap.platformsRemoved = zone.deltaEncoder.platformsRemoved(allPlatforms);
        }

        return snap;
    }

    /** Fallback for the brief window before the simulator is ready (rare). */
    private WorldSnapshot buildFallbackSnapshot(List<PlayerRecord> zonePlayers) {
        WorldSnapshot snap = new WorldSnapshot();
        snap.frame  = zone.frame.get();
        snap.seed   = zone.seed;
        snap.hubId  = zone.hubId;
        for (PlayerRecord pr : zonePlayers) {
            PlayerState ps = new PlayerState();
            ps.playerId  = pr.playerId;
            ps.slot      = pr.slot;
            ps.posX      = pr.posX;
            ps.posY      = pr.posY;
            ps.velX      = pr.velX;
            ps.velY      = pr.velY;
            ps.health    = pr.health;
            ps.facing    = pr.facing;
            ps.isDead    = pr.isDead;
            ps.animState = pr.animState;
            snap.players.add(ps);
        }
        return snap;
    }

    private List<PlayerRecord> playersInZone() {
        List<PlayerRecord> result = new ArrayList<>(zone.playerIds.size());
        for (String pid : zone.playerIds) {
            PlayerRecord pr = session.players.get(pid);
            if (pr != null) result.add(pr);
        }
        return result;
    }
}
