blank_issues_enabled: false

contact_links:
  - name: Report a bug or give feedback (Public)
    url: https://github.com/VainAsher/indie-ninja-feedback/issues/new/choose
    about: Submit player-facing bug reports, feature requests, and gameplay feedback here.
