#!/usr/bin/env python3
"""
dialogues_json_to_yarn.py — Convert Shadow Ascent dialogues.json → Yarn Spinner .yarn files.

Each top-level dialogue tree in data/dialogues.json becomes one .yarn file
in data/dialogues/<tree_id>.yarn.

Yarn Spinner node format:
  title: <node_id>
  tags: [root]          (root node only)
  root: <root_node_id>  (first node in file only — custom metadata)
  ---
  Speaker: dialogue text
  -> Choice text
      <<jump next_node>>
  <<stop>>
  ===

Mapping rules:
  node.text / node.speaker    → "Speaker: text"
  node.choices[].choice_text  → "-> choice text"
  choice.requires             → "<<if $<requires>>>"  (condition on choice line)
  choice.on_select_event      → "<<fire_event <event>>>" (inside choice branch)
  choice.next_node_id = null  → "<<stop>>"
  node.next_node_id (no choices) → "<<jump next>>" or "<<stop>>"
  node.on_exit_event          → "<<fire_event <event>>>"

Usage:
    python tools/dialogues_json_to_yarn.py [--input data/dialogues.json] [--outdir data/dialogues]
"""

import sys
import json
import argparse
from pathlib import Path


def escape_yarn(text: str) -> str:
    """Escape special characters that could break Yarn parsing."""
    return text.replace("//", "\\/\\/")


def node_to_yarn(node: dict, is_root: bool) -> str:
    node_id = node.get("node_id", node.get("nodeId", "unknown"))
    speaker = node.get("speaker", "")
    text = node.get("text", "")
    choices = node.get("choices", [])
    next_id = node.get("next_node_id")
    exit_event = node.get("on_exit_event")

    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines.append(f"title: {node_id}")
    if is_root:
        lines.append("tags: root")
    lines.append("---")

    # ── Dialogue line ─────────────────────────────────────────────────────────
    safe_text = escape_yarn(text)
    if speaker:
        lines.append(f"{speaker}: {safe_text}")
    elif safe_text:
        lines.append(safe_text)

    # ── On-exit event (fires before branching) ────────────────────────────────
    if exit_event:
        lines.append(f"<<fire_event {exit_event}>>")

    # ── Choices or auto-advance ───────────────────────────────────────────────
    if choices:
        for choice in choices:
            choice_text = escape_yarn(choice.get("choice_text", ""))
            next_node = choice.get("next_node_id")
            requires = choice.get("requires")
            select_event = choice.get("on_select_event")

            if requires:
                lines.append(f"-> {choice_text} <<if ${requires}>>")
            else:
                lines.append(f"-> {choice_text}")

            # Branch body (indented 4 spaces)
            if select_event:
                lines.append(f"    <<fire_event {select_event}>>")
            if next_node:
                lines.append(f"    <<jump {next_node}>>")
            else:
                lines.append("    <<stop>>")
    else:
        # Auto-advance
        if next_id:
            lines.append(f"<<jump {next_id}>>")
        else:
            lines.append("<<stop>>")

    lines.append("===")
    return "\n".join(lines)


def tree_to_yarn(tree_id: str, tree: dict) -> str:
    root_node_id = tree.get("root_node_id", "")
    nodes = tree.get("nodes", {})

    yarn_nodes: list[str] = []

    # Root node first, then all others in insertion order
    if root_node_id and root_node_id in nodes:
        yarn_nodes.append(node_to_yarn(nodes[root_node_id], is_root=True))

    for nid, node in nodes.items():
        if nid == root_node_id:
            continue
        yarn_nodes.append(node_to_yarn(node, is_root=False))

    header_comment = (
        f"// Yarn Spinner — generated by tools/dialogues_json_to_yarn.py\n"
        f"// Source dialogue: {tree_id}\n"
        f"// root_node_id: {root_node_id}\n"
    )
    return header_comment + "\n".join(yarn_nodes)


def convert(input_path: Path, out_dir: Path) -> int:
    if not input_path.exists():
        print(f"ERROR: input file not found: {input_path}", file=sys.stderr)
        return 1

    try:
        with open(input_path, encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"ERROR: JSON parse error: {e}", file=sys.stderr)
        return 1

    out_dir.mkdir(parents=True, exist_ok=True)
    converted = 0
    errors = 0

    for tree_id, tree in data.items():
        try:
            yarn_text = tree_to_yarn(tree_id, tree)
            out_path = out_dir / f"{tree_id}.yarn"
            out_path.write_text(yarn_text, encoding="utf-8")
            node_count = len(tree.get("nodes", {}))
            print(f"  {tree_id}.yarn  ({node_count} nodes)")
            converted += 1
        except Exception as e:
            print(f"ERROR converting {tree_id}: {e}", file=sys.stderr)
            errors += 1

    print(f"\nConverted {converted} dialogue tree(s) to {out_dir}/")
    if errors:
        print(f"{errors} error(s) encountered.")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert Shadow Ascent dialogues.json to Yarn Spinner .yarn files."
    )
    parser.add_argument(
        "--input",
        default="data/dialogues.json",
        help="Path to dialogues.json (default: data/dialogues.json)",
    )
    parser.add_argument(
        "--outdir",
        default="data/dialogues",
        help="Output directory for .yarn files (default: data/dialogues)",
    )
    args = parser.parse_args()
    return convert(Path(args.input), Path(args.outdir))


if __name__ == "__main__":
    sys.exit(main())
